In [ ]:
import json

Fuzzy Sets: Fuzzy Set is a Set where every key is associated with value, which is between 0 to 1 based on the certainity .

Union: degree_of_membership(Y) = max(degree_of_membership(A), degree_of_membership(B)) 

In [ ]:
def fuzzy_union(A, B):
    union = dict()
    for key in A:
        if key in B:
            union[key] = max(A[key], B[key])
        else:
            union[key] = A[key]
    for key in B:
        if key not in union:
            union[key] = B[key]
    return union

Intersection: degree_of_membership(Y) = min(degree_of_membership(A), degree_of_membership(B)) 

In [ ]:
def fuzzy_intersection(A, B):
    intersection = dict()
    for key in A:
        if key in B:
            intersection[key] = min(A[key], B[key])
    return intersection

Complement: degree_of_membership(Y) = 1 - degree_of_membership(A)

In [ ]:
def fuzzy_complement(A):
    complement = dict()
    for key in A:
        complement[key] = 1 - A[key]
    return complement

degree_of_membership(Y) = min(degree_of_membership(A), 1- degree_of_membership(B)) 

In [ ]:
def fuzzy_difference(A, B):
    difference = dict()
    for key in A:
        if key in B:
            difference[key] = min(A[key], 1 - B[key])
        else:
            difference[key] = A[key]
    for key in B:
        if key not in difference:
            difference[key] = 1 - B[key]
    return difference

µA1 x A2 x…x An (x1, x2,…, xn) = min [µA1 (x1), µA2 (x2), …. µAn (xn)]

In [ ]:
def fuzzy_cartesian_product(A, B):
    cartesian_product = dict()
    for a in A:
        cartesian_product[a] = dict()
        for b in B:
            cartesian_product[a][b] = min(A[a], B[b])
    return cartesian_product

In [ ]:
ans00 = max(min(R00, S00), min(R01, S10))
ans01 = max(min(R00, S10), min(R01, S11))

def max_min_composition(R, S):
    m, n = len(R), len(R[0])
    o = len(S[0])
    composition = dict()
    for i in range(m):
        composition[i] = dict()
        for k in range(o):
            composition[i][k] = max([min(R[i][j], S[j][k]) for j in range(n)])
    return composition

In [ ]:
def main():
    A = dict()
    B = dict()
    with open("./input_sets.json") as f:
        sets = json.load(f)
        A = sets["A"]
        B = sets["B"]
    if (type(A) is dict) and (type(B) is dict):
        print("A:", A)
        print("B:", B)

        union = fuzzy_union(A, B)
        print("\nUnion:", union)

        intersection = fuzzy_intersection(A, B)
        print("\nIntersection:", intersection)

        comp_A, comp_B = fuzzy_complement(A), fuzzy_complement(B)
        print("\nComplement of A:", comp_A)
        print("Complement of B:", comp_B)

        difference = fuzzy_difference(A, B)
        print("\nDifference:", difference)

        cartesian_product = fuzzy_cartesian_product(A, B)
        print("\nCartesian product:", cartesian_product, sep="\n")

        R = None
        S = None
        with open("./relations.json") as f:
            relations = json.load(f)
            R = relations["R"]
            S = relations["S"]
        print("\nR: " + str(R))
        print("S: " + str(S))
        composition = max_min_composition(R, S)
        print("\nMax-min composition:", composition, sep="\n")
    else:
        print("Fuzzy sets should be in the form of a dictionary")

In [ ]:
%%time
main()

A: {'a': 0.6, 'b': 0.1, 'c': 0.9, 'd': 0.4}
B: {'a': 0.5, 'b': 0.3, 'c': 0.3, 'd': 0.2}

Union: {'a': 0.6, 'b': 0.3, 'c': 0.9, 'd': 0.4}

Intersection: {'a': 0.5, 'b': 0.1, 'c': 0.3, 'd': 0.2}

Complement of A: {'a': 0.4, 'b': 0.9, 'c': 0.09999999999999998, 'd': 0.6}
Complement of B: {'a': 0.5, 'b': 0.7, 'c': 0.7, 'd': 0.8}

Difference: {'a': 0.5, 'b': 0.1, 'c': 0.7, 'd': 0.4}

Cartesian product:
{'a': {'a': 0.5, 'b': 0.3, 'c': 0.3, 'd': 0.2}, 'b': {'a': 0.1, 'b': 0.1, 'c': 0.1, 'd': 0.1}, 'c': {'a': 0.5, 'b': 0.3, 'c': 0.3, 'd': 0.2}, 'd': {'a': 0.4, 'b': 0.3, 'c': 0.3, 'd': 0.2}}

R: [[0.6, 0.3], [0.2, 0.9]]
S: [[1, 0.5, 0.3], [0.8, 0.4, 0.7]]

Max-min composition:
{0: {0: 0.6, 1: 0.5, 2: 0.3}, 1: {0: 0.8, 1: 0.4, 2: 0.7}}
Wall time: 7 ms


# Scikit-fuzzy api implementation

In [ ]:
import skfuzzy as fuzz
import numpy as np

In [ ]:
def convert_dict(A,B):
    A_x,A_mfx,B_x,B_mfx = [],[],[],[]
    for key in A:
        A_x.append(key)
        A_mfx.append(A[key])
    for key in B:
        B_x.append(key)
        B_mfx.append(B[key])
    return np.array(A_x),np.array(A_mfx),np.array(B_x),np.array(B_mfx)

In [ ]:
def skfuzzy_main():
    A = dict()
    B = dict()
    with open("./input_sets.json") as f:
        sets = json.load(f)
        A = sets["A"]
        B = sets["B"]
    if (type(A) is dict) and (type(B) is dict):
        print("A:", A)
        print("B:", B)
        
        A_x, A_mfx, B_x, B_mfx = convert_dict(A,B)
        union = fuzz.fuzzy_or(A_x, A_mfx, B_x, B_mfx)
        print("\nUnion:", union)

        intersection = fuzz.fuzzy_and(A_x, A_mfx, B_x, B_mfx)
        print("\nIntersection:", intersection)

        comp_A, comp_B = fuzz.fuzzy_not(A_mfx), fuzz.fuzzy_not(B_mfx)
        print("\nComplement of A:", comp_A)
        print("Complement of B:", comp_B)

        cartesian_product = fuzz.cartprod(A_mfx, B_mfx)
        print("\nCartesian product:", cartesian_product, sep="\n")

        R = None
        S = None
        with open("./relations.json") as f:
            relations = json.load(f)
            R = relations["R"]
            S = relations["S"]
            R=np.array([np.array(x) for x in R])
            S=np.array([np.array(x) for x in S])
        print("\nR: " + str(R))
        print("S: " + str(S))
        composition = fuzz.maxmin_composition(R, S)
        print("\nMax-min composition:", composition, sep="\n")
    else:
        print("Fuzzy sets should be in the form of a dictionary")

In [ ]:
%%time
skfuzzy_main()

A: {'a': 0.6, 'b': 0.1, 'c': 0.9, 'd': 0.4}
B: {'a': 0.5, 'b': 0.3, 'c': 0.3, 'd': 0.2}

Union: (array(['a', 'b', 'c', 'd'], dtype='<U1'), array([0.6, 0.3, 0.9, 0.4]))

Intersection: (array(['a', 'b', 'c', 'd'], dtype='<U1'), array([0.5, 0.1, 0.3, 0.2]))

Complement of A: [0.4 0.9 0.1 0.6]
Complement of B: [0.5 0.7 0.7 0.8]

Cartesian product:
[[0.5 0.3 0.3 0.2]
 [0.1 0.1 0.1 0.1]
 [0.5 0.3 0.3 0.2]
 [0.4 0.3 0.3 0.2]]

R: [[0.6 0.3]
 [0.2 0.9]]
S: [[1.  0.5 0.3]
 [0.8 0.4 0.7]]

Max-min composition:
[[0.6 0.5 0.3]
 [0.8 0.4 0.7]]
Wall time: 15 ms
